### ISSUE TITLE
engineerモデルの実装

### ISSUE THREAD

**Issue by hidetora-max** [hidetora-max/BoxCode#6]
# Todo

- [x] Engineerテーブルにカラムを追加(token/avatar/name/birth/info/job_seeking/)

- [x] EngineerモデルのRspecテスト（バリデーション）(RED)

- [x] Engineerモデルのバリデーション実装（GREEN)

- [x] carrierwave, minimagick, uploader の導入

- [x] carrywaveの設定

- [x] デフォルト画像の実装
